// Generated by IcedCoffeeScript 108.0.11
(function() {
  var Stampery, iced, stampery, __iced_k, __iced_k_noop;

  iced = require('iced-runtime');
  __iced_k = __iced_k_noop = function() {};

  Stampery = require('./index');

  stampery = new Stampery('user-secret');

  stampery.on('proof', function(hash, proof) {
    var valid, ___iced_passed_deferral, __iced_deferrals, __iced_k;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    console.log("\nReceived proof for\n" + hash + "\n", JSON.stringify(proof, null, 2));
    (function(_this) {
      return (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "/home/johann/Workspace/Stampery/node/example.iced"
        });
        stampery.prove(hash, proof, __iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              return valid = arguments[0];
            };
          })(),
          lineno: 7
        }));
        __iced_deferrals._fulfill();
      });
    })(this)((function(_this) {
      return function() {
        return console.log('Proof validity:', valid);
      };
    })(this));
  });

  stampery.on('error', function(err) {
    return console.log('woot: ', err);
  });

  stampery.on('ready', function() {
    var hash, random, ___iced_passed_deferral, __iced_deferrals, __iced_k;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    random = Math.random().toString(36).slice(2);
    (function(_this) {
      return (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "/home/johann/Workspace/Stampery/node/example.iced"
        });
        stampery.hash("The piano has been drinking " + random, __iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              return hash = arguments[0];
            };
          })(),
          lineno: 15
        }));
        __iced_deferrals._fulfill();
      });
    })(this)((function(_this) {
      return function() {
        return stampery.stamp(hash);
      };
    })(this));
  });

}).call(this);
